#!/usr/bin/env python3
import os
import random
import re
from glob import glob

import click
from guizero import App, Text, Picture, PushButton
from PIL import Image


def read_file(fn):
    with open(fn, 'r') as f:
        return f.read()


def random_file():
    png_file = random.choice(png_files)

    prefix = re.sub(r'(\.\w+)?\.png$', '', png_file)
    gt_file = prefix + '.gt.txt'
    pred_file = prefix + '.pred.txt'
    gt = read_file(gt_file).rstrip()
    try:
        pred = read_file(pred_file).rstrip()
    except FileNotFoundError:
        pred = ''

    gt_file_display = os.path.basename(gt_file)
    pred_color = 'green' if gt == pred else 'red'
    image = Image.open(png_file)
    app_padding = 10
    app_width = max(app.width, image.width + app_padding)

    app.width = app_width
    filename.value = gt_file_display
    pic.width = image.size[0]
    pic.height = image.size[1]
    pic.image = image
    text_gt.value = gt
    text_pred.value = pred
    text_pred.text_color = pred_color


@click.command()
@click.argument('directory')
def line_gt_viewer(directory):
    """Display the .png/.gt.txt line ground truth in DIRECTORY"""
    global png_files, app, filename, pic, text_gt, text_pred

    png_files = glob(os.path.join(directory, '*.png'))
    app = App('A very basic OCR line GT viewer')

    filename = Text(app)
    pic = Picture(app)
    text_gt = Text(app)
    text_pred = Text(app)
    button = PushButton(app, text="I'm feeling Iucky", command=random_file)

    random_file()

    app.display()


if __name__ == '__main__':
    line_gt_viewer()
