#!/usr/bin/env python3
import os
import random
import re
from glob import glob
from guizero import App, Text, Picture, PushButton

basedir = '/srv/data/clemens/GT4HistOCR/corpus/dta19/1827-heine_lieder/'


def read_file(f):
    with open(f, 'r') as f:
        return f.read()


def random_file():
    png_file = random.choice(png_files)

    gt_file = re.sub(r'\..*?\.png', '.gt.txt', png_file)
    pred_file = re.sub(r'\..*?\.png', '.pred.txt', png_file)

    filename.value = os.path.basename(gt_file)
    pic.image = png_file
    text_gt.value = read_file(gt_file).rstrip()
    try:
        text_pred.value = read_file(pred_file).rstrip()

        if text_pred.value == text_gt.value:
            text_pred.text_color = 'green'
        else:
            text_pred.text_color = 'red'
    except Exception as e:
        print(e)
        text_pred.value = ''


png_files = glob(basedir + '*.png')

app = App('A very basic OCR line GT viewer')

filename = Text(app)
pic = Picture(app)
text_gt = Text(app)
text_pred = Text(app)
button = PushButton(app, text="I'm feeling Iucky", command=random_file)

random_file()

app.display()
