#!/usr/bin/env python3
import os
import random
import re
from glob import glob

import click
from guizero import App, Text, Picture, PushButton
from PIL import Image


def read_file(fn):
    with open(fn, 'r') as f:
        return f.read()


def random_file():
    png_file = random.choice(png_files)

    prefix = re.sub(r'(\.\w+)?\.png$', '', png_file)
    gt_file = prefix + '.gt.txt'
    pred_file = prefix + '.pred.txt'
    gt = read_file(gt_file).rstrip()
    try:
        pred = read_file(pred_file).rstrip()
    except FileNotFoundError:
        pred = ''

    gt_file_display = os.path.basename(gt_file)
    pred_color = 'green' if gt == pred else 'red'
    image = Image.open(png_file)
    app_padding = 10
    app_width = max(ui.app.width, image.width + app_padding)

    ui.app.width = app_width
    ui.filename.value = gt_file_display
    ui.pic.width = image.size[0]
    ui.pic.height = image.size[1]
    ui.pic.image = image
    ui.text_gt.value = gt
    ui.text_pred.value = pred
    ui.text_pred.text_color = pred_color


@click.command()
@click.argument('directory')
def line_gt_viewer(directory):
    """Display the .png/.gt.txt line ground truth in DIRECTORY"""
    global png_files

    png_files = glob(os.path.join(directory, '*.png'))

    ui.app = App('A very basic OCR line GT viewer')
    ui.filename = Text(ui.app)
    ui.pic = Picture(ui.app)
    ui.text_gt = Text(ui.app)
    ui.text_pred = Text(ui.app)
    ui.button = PushButton(ui.app, text="I'm feeling Iucky", command=random_file)

    random_file()

    ui.app.display()


class AttrDict(dict):
    """
    A dict with attributes

    Instead of writing ``foo['bar']``, write ``foo.bar``.
    """
    def __getattr__(self, item):
        return self[item]


ui = AttrDict()

if __name__ == '__main__':
    line_gt_viewer()
